# Generated by Django 5.1.4 on 2025-01-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100)),
                ('details_received', models.BooleanField(default=False)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('invoice_correct', models.BooleanField()),
                ('date_corrected', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
