# Generated by Django 5.1.4 on 2025-01-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bill_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
