# Generated by Django 5.1.4 on 2025-01-03 08:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_wrong_invoices(apps, schema_editor):
    Member = apps.get_model('myapp', 'Member')
    wronginvoice = apps.get_model('myapp', 'wronginvoice')

    # Assuming the old model is `Bill` with a field `wrong_invoice_number`
    for bill in Member.objects.filter(details_received = True,invoice_correct=False):  # Example query for wrong invoices
        wronginvoice.objects.create(bill_number=bill, balance=bill.balance)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_wronginvoice'),
    ]

    operations = [
        migrations.RunPython(migrate_wrong_invoices),
    ]
