# Generated by Django 5.1.4 on 2025-01-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wronginvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wronginvoice',
            name='bill_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
