# Generated by Django 5.1.4 on 2025-01-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_wronginvoice_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='invoice_correct',
            field=models.BooleanField(null=True),
        ),
    ]
